package io.github.auxen.dsp

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File
import java.util.zip.ZipFile

/** One entry of the bundled AutoEq database. */
data class AutoEqProfile(val index: Int, val name: String, val source: String, val rig: String)

/**
 * Read-only access to the bundled AutoEq database
 * (assets/autoeq.zip, generated by android/scripts/generate-autoeq-asset.sh).
 *
 * The 8,850-name index is held in memory (~1 MB) after [ensureLoaded];
 * profile bodies are read from the zip on demand. The asset is copied to
 * cacheDir once because ZipFile needs a real file path — asset streams
 * can't be random-accessed.
 */
class AutoEqRepository(context: Context) {
    private val appContext = context.applicationContext
    private val json = Json { ignoreUnknownKeys = true }

    @Serializable
    private data class IndexEntry(val name: String, val source: String = "", val rig: String = "")

    @Serializable
    private data class Index(val profiles: List<IndexEntry> = emptyList())

    @Volatile
    private var profiles: List<AutoEqProfile> = emptyList()

    /** Number of profiles loaded; 0 before [ensureLoaded] completes. */
    val profileCount: Int get() = profiles.size

    /** Parses the bundled index once (IO dispatcher); subsequent calls no-op. */
    suspend fun ensureLoaded() {
        if (profiles.isNotEmpty()) return
        withContext(Dispatchers.IO) {
            ZipFile(cachedZip()).use { zip ->
                val entry = zip.getEntry("index.json") ?: error("autoeq.zip missing index.json")
                val parsed = json.decodeFromString<Index>(
                    zip.getInputStream(entry).bufferedReader().readText(),
                )
                profiles = parsed.profiles.mapIndexed { i, e -> AutoEqProfile(i, e.name, e.source, e.rig) }
            }
        }
    }

    /** Case-insensitive substring search on name; blank query returns an empty list. */
    fun search(query: String, limit: Int = 50): List<AutoEqProfile> {
        val trimmed = query.trim()
        if (trimmed.isEmpty()) return emptyList()
        return profiles.asSequence()
            .filter { it.name.contains(trimmed, ignoreCase = true) }
            .take(limit)
            .toList()
    }

    /** Reads `profiles/<index>.txt` from the asset zip (AutoEq ParametricEq text format). */
    suspend fun profileText(profile: AutoEqProfile): String = withContext(Dispatchers.IO) {
        ZipFile(cachedZip()).use { zip ->
            val entry = zip.getEntry("profiles/${profile.index}.txt")
                ?: error("Missing profile body for ${profile.name}")
            zip.getInputStream(entry).bufferedReader().readText()
        }
    }

    /**
     * Returns the cached copy of `assets/autoeq.zip`, (re)copying it when stale.
     *
     * cacheDir survives app updates, so a "copy once if missing" check would
     * keep serving an old database after the bundled asset changes. We instead
     * re-copy whenever the cached file's length differs from the asset's
     * uncompressed length ([assetZipLength]) — cheap to obtain and, since the
     * copy is byte-for-byte, a reliable change signal across updates (two
     * different AutoEq database builds virtually always differ in size).
     */
    private fun cachedZip(): File {
        val cached = File(appContext.cacheDir, "autoeq.zip")
        if (!cached.exists() || cached.length() != assetZipLength()) {
            appContext.assets.open("autoeq.zip").use { input ->
                cached.outputStream().use { input.copyTo(it) }
            }
        }
        return cached
    }

    /**
     * Uncompressed length of the bundled `autoeq.zip` asset. Prefers the asset
     * file descriptor; AGP-compressed assets can't be opened as an fd, so we
     * fall back to the asset stream's `available()`, which reports the full
     * uncompressed length for an AssetManager stream.
     */
    private fun assetZipLength(): Long = runCatching {
        appContext.assets.openFd("autoeq.zip").use { it.length }
    }.getOrElse {
        appContext.assets.open("autoeq.zip").use { it.available().toLong() }
    }
}
